spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://pnl-fatpc-accounting.cb1o9kaae1km.ap-northeast-1.rds.amazonaws.com:3306/zsystem?zerodatetimebehavior=Converttonull&serverTimezone=Asia/Tokyo
    username: 3sapp
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver